name: stev-report

on:
  push:
    tags:
      - "v*"
    branches:
      - 'main'

jobs:
  build-windows-image:
    name: 'Build Windows Image'
    strategy:
      matrix:
        os: ['windows-latest']
        include:
          - os: 'windows-latest'
            label: 'windows'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup GraalVM and Native Image'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Native Image'
        run: |
          .\mvnw.cmd -Pnative -DskipTests native:compile

      - name: 'List Target'
        run: |
          Get-ChildItem target

      - name: 'Publish Native Image'
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: 'stev-report'
          path: target/stev-report.exe

      - name: 'Create Release and Upload Asset'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Initial Windows release
          draft: false
          prerelease: false
          files: |
            target/stev-report.exe
            target/report.properties

      - name: 'Write Upload URL To File'
        run: |
          echo "Release URL: https://github.com{{ github.repository }}/releases/tag/${{ github.ref_name }}" > upload_url.txt

      - name: 'Publish Upload URL Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'upload_url.txt'
          path: 'upload_url.txt'
